### ISSUE TITLE
Vanilla Article template

### ISSUE THREAD

**Issue by stevengogogo** [sosiristseng/template-pandoc-tectonic#5]
Required features
------------------
- [ ] auther-year citation
- [ ] support `subfigure` package
- [ ] reference of figure, equation
- [ ] customized border by `\usepackage{gemoetry}`

Purpose
---------
- for submission to Arxiv and course final project

**Comment by sosiristseng** [comment]
Could citations be done by `citeproc` filter in `pandoc`?
